#[[[cog
#  import cog
#]]]
#[[[end]]]

FROM cantora/arch

RUN mkdir /root/docker-build/
ADD ./setup.tar.gz /root/docker-build/
RUN rm -f /root/docker-build/*.sig
RUN pacman-key --init
RUN pacman --config /dev/null \
           --noconfirm -U  /root/docker-build/blackarch-keyring.pkg.tar.xz
RUN printf '\n[blackarch]\nServer = %s/$repo/os/$arch\n' \
              'http://mirror.jmu.edu/blackarch/' \
           >> /etc/pacman.conf

RUN pacman -Syyu --noconfirm
RUN pacman -S --noconfirm sudo gdb git tree sudo

RUN groupadd sudo
RUN printf '\n%%sudo   ALL=(ALL) ALL\n' >> /etc/sudoers
#[[[cog
#   
#  if not cryptpass or len(cryptpass) < 1:
#    raise Exception("invalid cryptpass")
#
#  usercmd = "RUN useradd -G sudo -m qwer -p '%s'" % cryptpass
#  cog.outl(usercmd)
#]]]
#[[[end]]]
